name: Request API

on: workflow_call

jobs:
  api-request:
    runs-on: ubuntu-latest
    # environment: dev

    steps:
      - name: Mask secrets in logs
        run: |
          echo "::add-mask::${{ vars.TEST }}"
          echo "${{ vars.TEST }}"
          echo "{\"username\": \"${{ secrets.USERNAME }}\", \"password\": \"${{ secrets.PASSWORD }}\", \"client_id\": \"${{ secrets.CLIENT_ID }}\",\"client_secret\": \"${{ secrets.CLIENT_SECRET }}\"}" > credentials.json
          cat credentials.json
      - name: Obter token de autenticação
        id: obter_token
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          response=$(curl -X POST ${{ vars.TOKEN_URL }} \
            -d "grant_type=password" \
            -d "client_id=${CLIENT_ID}" \
            -d "client_secret=${CLIENT_SECRET}" \
            -d "username=${USERNAME}" \
            -d "password=${PASSWORD}")
          echo "response=$response"
          echo ${{ secrets.CLIENT_ID }}
          token=$(echo $response | jq -r '.access_token')
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Usar o token de autenticação
        run: |
          echo "Token de autenticação: ${{ steps.obter_token.outputs.token }}"
          # Exemplo de uso do token para fazer uma requisição API