name: Request API

on: workflow_call

jobs:
  api-request:
    runs-on: ubuntu-latest
    environment:
        name: master

    steps:
      - name: Mask secrets in logs
        run: |
          echo "{\"username\": \"${{ secrets.USERNAME }}\", \"password\": \"${{ secrets.PASSWORD }}\", \"client_id\": \"${{ secrets.CLIENT_ID }}\",\"client_secret\": \"${{ secrets.CLIENT_SECRET }}\"}" > credentials.json

      - name: Obter token de autenticação
        id: obter_token
        run: |
          USERNAME=$(jq -r '.username' credentials.json)
          PASSWORD=$(jq -r '.password' credentials.json)
          CLIENT_ID=$(jq -r '.client_id' credentials.json)
          CLIENT_SECRET=$(jq -r '.client_secret' credentials.json)
          response=$(curl -X POST ${{ vars.TOKEN_URL }} \
            -d "grant_type=password" \
            -d "client_id=$CLIENT_ID" \
            -d "client_secret=$CLIENT_SECRET" \
            -d "username=$USERNAME" \
            -d "password=$PASSWORD")
          echo "response=$response"
          token=$(echo $response | jq -r '.access_token')
          echo "::set-output name=token::$token"

      - name: Usar o token de autenticação
        run: |
          echo "Token de autenticação: ${{ steps.obter_token.outputs.token }}"
          # Exemplo de uso do token para fazer uma requisição API