name: Insert data

on: workflow_call

jobs:
  insert_pep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Install Node'
      uses: actions/setup-node@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get File PEP
      uses: actions/download-artifact@v4
      with:
        name: pep.parquet
        path: ${{ runner.temp }}/pep-parquet

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install jq

    - name: Install dependencies
      run: |
        pip install pandas
        pip install pyarrow
        pip install pandasql

    - name: 'Install Salesforce CLI'
        run: |
          npm install @salesforce/cli --global
          sf version

    - name: 'Populate auth file with SFDX_URL secret of the integration and staging orgs'
        shell: bash
        run: |
          echo ${{ secrets.UAT_URL }} > ./SECRET.txt

      - name: 'Authenticate to Org'
        run: | 
          sf org login sfdx-url -f ./SECRET.txt -s -a integration

      - name: Generate Authentication Token
        id: generate_token
        run: |
          AUTH_TOKEN=$(sfdx force:org:display --json | jq -r '.result.accessToken')
          echo "::set-output name=auth_token::$AUTH_TOKEN"
      
      - name: Log files
        run: ls ${{ runner.temp }}/pep-parquet/