name: Prepare data

on: workflow_call

jobs:
  data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get File PEP
      uses: actions/download-artifact@v4
      with:
        name: pep-file
        path: ${{ runner.temp }}/downloads_pep
      
    - name: Get File CSNU
      uses: actions/download-artifact@v4
      with:
        name: csnu-file
        path: ${{ runner.temp }}/downloads_csnu

    - name: Display structure of downloaded files
      run: ls -R ${{ runner.temp }}
    
